### ISSUE TITLE
DefaultIntegrationToProjectConverterTest test fails when run on CI environment

### ISSUE THREAD

**Issue by iocanel** [syndesisio/syndesis-rest#168]
Apparently, the converter is using [camel-catalog-maven](https://github.com/apache/camel/blob/master/platforms/camel-catalog-maven/) which uses Grape/Ivy.

It seems that when run inside a Jenkins (via [Kubernetes Plugin](https://github.com/jenkinsci/kubernetes-plugin)). For reasons I don't fully understand it misreads the local repo path (it contains `?`) and this seems to drive grape mad.

Explicitly settings the maven local repo path, doesn't solve the issue.

The exception is the following:

Running com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Local Ivy config file 'jar:file:/home/jenkins/workspace/Hat_iPaaS_ipaas-rest_master-MOCTL7CJDHTHPHSLP3WDVMV2YS6A6N67D2M4FLGXUNEB24MFX7VA/%3f/.m2/repository/org/codehaus/groovy/groovy/2.4.9/groovy-2.4.9.jar!/groovy/grape/defaultGrapeConfig.xml' appears corrupt - ignoring it and using default config instead
Error was: failed to load settings from jar:file:/home/jenkins/workspace/Hat_iPaaS_ipaas-rest_master-MOCTL7CJDHTHPHSLP3WDVMV2YS6A6N67D2M4FLGXUNEB24MFX7VA/%3f/.m2/repository/org/codehaus/groovy/groovy/2.4.9/groovy-2.4.9.jar!/groovy/grape/defaultGrapeConfig.xml: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
Mar 10, 2017 12:29:55 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.3.4.Final
Local Ivy config file 'jar:file:/home/jenkins/workspace/Hat_iPaaS_ipaas-rest_master-MOCTL7CJDHTHPHSLP3WDVMV2YS6A6N67D2M4FLGXUNEB24MFX7VA/%3f/.m2/repository/org/codehaus/groovy/groovy/2.4.9/groovy-2.4.9.jar!/groovy/grape/defaultGrapeConfig.xml' appears corrupt - ignoring it and using default config instead
Error was: failed to load settings from jar:file:/home/jenkins/workspace/Hat_iPaaS_ipaas-rest_master-MOCTL7CJDHTHPHSLP3WDVMV2YS6A6N67D2M4FLGXUNEB24MFX7VA/%3f/.m2/repository/org/codehaus/groovy/groovy/2.4.9/groovy-2.4.9.jar!/groovy/grape/defaultGrapeConfig.xml: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.374 sec <<< FAILURE! - in com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest
testConvertFromJson(com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest)  Time elapsed: 1.864 sec  <<< ERROR!
java.text.ParseException: failed to load settings from jar:file:/home/jenkins/workspace/Hat_iPaaS_ipaas-rest_master-MOCTL7CJDHTHPHSLP3WDVMV2YS6A6N67D2M4FLGXUNEB24MFX7VA/%3f/.m2/repository/org/codehaus/groovy/groovy/2.4.9/groovy-2.4.9.jar!/groovy/grape/defaultGrapeConfig.xml: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
	at com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest.testConvertFromJson(DefaultIntegrationToProjectConverterTest.java:74)
Caused by: java.lang.IllegalArgumentException: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
	at com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest.testConvertFromJson(DefaultIntegrationToProjectConverterTest.java:74)
Caused by: java.lang.reflect.InvocationTargetException
	at com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest.testConvertFromJson(DefaultIntegrationToProjectConverterTest.java:74)
Caused by: java.lang.IllegalArgumentException: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
	at com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest.testConvertFromJson(DefaultIntegrationToProjectConverterTest.java:74)

testConvert(com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest)  Time elapsed: 0.401 sec  <<< ERROR!
java.text.ParseException: failed to load settings from jar:file:/home/jenkins/workspace/Hat_iPaaS_ipaas-rest_master-MOCTL7CJDHTHPHSLP3WDVMV2YS6A6N67D2M4FLGXUNEB24MFX7VA/%3f/.m2/repository/org/codehaus/groovy/groovy/2.4.9/groovy-2.4.9.jar!/groovy/grape/defaultGrapeConfig.xml: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
	at com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest.testConvert(DefaultIntegrationToProjectConverterTest.java:47)
Caused by: java.lang.IllegalArgumentException: impossible to add configured child for ivy on class org.apache.ivy.plugins.resolver.FileSystemResolver: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
	at com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest.testConvert(DefaultIntegrationToProjectConverterTest.java:47)
Caused by: java.lang.reflect.InvocationTargetException
	at com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest.testConvert(DefaultIntegrationToProjectConverterTest.java:47)
Caused by: java.lang.IllegalArgumentException: ivy pattern must be absolute: ?/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml
	at com.redhat.ipaas.project.converter.DefaultIntegrationToProjectConverterTest.testConvert(DefaultIntegrationToProjectConverterTest.java:47)

**Comment by iocanel** [comment]
It seems that we need to explicity set the following system properties:

- `user.home`
- `maven.repo.local`

**Comment by iocanel** [comment]
Even when we set those properties right, we still have errors. After digging inside the Ivy source, I think that the problem is related to the way they reading resources from within the jar: 

They get the resource as url and pass it to the `xmlParser` however, this will fail if the path contains characters that are compatible with the url encoding.

We've hit the issue before in the kubernetes-client and fixed it with this: https://github.com/fabric8io/kubernetes-client/commit/1a0ab37f613d497a8c53b4a0c99809ee9841a332

I suggest we add a junit assume that the path is clean so that the build won't fail in Jenkins.
