### ISSUE TITLE
Creating integration from twitter example to salesforce upsert fails

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-rest#272]
When running e2e tests in ipaas-ui, we get following error
![error](https://cloud.githubusercontent.com/assets/8707241/24613558/ee75b958-1888-11e7-8079-cadd69659275.png)

and in the ipaas-rest log I see:
```
Principal is: org.keycloak.adapters.springsecurity.token.KeycloakAuthenticationToken@42e08d3b: Principal: 0a0b1b24-77c6-4822-8623-b26ca515d8c1; Credentials: [PROTECTED]; Authenticated: true; Details: org.keycloak.adapters.springsecurity.account.SimpleKeycloakAccount@3ac86e84; Not granted any authorities
Downloading Maven GAV: com.redhat.ipaas:twitter-mention-connector:0.3.3
Downloading Maven GAV: com.redhat.ipaas:salesforce-create-opportunity-connector:0.3.3
2017-04-03 11:57:01.628  WARN [-,b253e472ab99898f,b253e472ab99898f,false] 1 --- [ XNIO-3 task-17] o.a.c.c.m.DefaultMavenArtifactProvider   : Error during add components from artifact com.redhat.ipaas:salesforce-create-opportunity-connector:0.3.3 due Error grabbing Grapes -- [unresolved dependency: com.redhat.ipaas#salesforce-create-opportunity-connector;0.3.3: not found]

java.lang.RuntimeException: Error grabbing Grapes -- [unresolved dependency: com.redhat.ipaas#salesforce-create-opportunity-connector;0.3.3: not found]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_111]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_111]
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83) ~[groovy-2.4.9.jar!/:2.4.9]
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77) ~[groovy-2.4.9.jar!/:2.4.9]
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84) ~[groovy-2.4.9.jar!/:2.4.9]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60) ~[groovy-2.4.9.jar!/:2.4.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235) ~[groovy-2.4.9.jar!/:2.4.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247) ~[groovy-2.4.9.jar!/:2.4.9]
at groovy.grape.GrapeIvy.getDependencies(GrapeIvy.groovy:424) ~[groovy-2.4.9.jar!/:2.4.9]
```

**Comment by jludvice** [comment]
Once, when I tried to click "Publish" button again, then it passed.

**Comment by KurtStam** [comment]
We 'build' the project and as one of steps the camel connectors are pulled down from maven using Grapes. It looks like this is subject to external resources not (always) being available. 

Two comments:
- In the async implementation we would log the error and then try again in a minutes time, so it could get resolved if it's just a temporary issue
- We should make sure we have an integration test for each for the connectors to make sure they can be downloaded and we should collect the response times. Maybe we also need to make sure these connectors get cached in the local .m2 repo so it's more likely to get downloaded quickly.

Leaving this open so we discuss this some more.

**Comment by jludvice** [comment]
@KurtStam do you have any estimate on how long it may take us to create integration in average?
UX team would like to know this for https://github.com/redhat-ipaas/ipaas-ui/issues/373.
They are considering some options to display progress when user clicks on publish integration.

**Comment by KurtStam** [comment]
@jludvice From what I've seen it's around 15 seconds or so. But it depends on the workload and availability of things like GitHub and OpenShift. If things fail, we will write a message into the integration (statusMessage) and try again periodically (every minute). So let's say if you're github creds are wrong (or GitHub is offline) then it should say in that message. You have then time to fix them, and it will retry. So it can take very much longer in situations like these. The UI can subscribe to update events on the integration to show updates to the statusMessage and currentStatus.

**Comment by kahboom** [comment]
For some reason this isn't working for me either.. I can't create an integration at all since the last demo I did lol.. I must be doing something wrong. Just keep getting back a 500 internal server error. Tried both 'save' and 'publish' with different connection types to no avail.

**Comment by rhuss** [comment]
The 500 error is due to a problem running the OpenShift build (see https://github.com/redhat-ipaas/ipaas-rest/issues/297). However I don't get back an error dialog except when I press publish a **second** time. then the error dialog appears + a second publish is triggered. Seems like a refresh issue here for the error.
