### ISSUE TITLE
Running build for create integration gives error

### ISSUE THREAD

**Issue by ipaas-demo-rhuss** [syndesisio/syndesis-rest#297]
When creating a new integration (Twitter Mention, Log "Hello world", Saleforce Upsert) then GitHub repo and files are created but when running the OpenShift build this exception occurs:

```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://ipaas-openshift-proxy.myproject.svc/oapi/v1/namespaces/myproject/imagestreams/s2i-java. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:320) ~[kubernetes-client-2.2.7.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:267) ~[kubernetes-client-2.2.7.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:239) ~[kubernetes-client-2.2.7.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232) ~[kubernetes-client-2.2.7.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:228) ~[kubernetes-client-2.2.7.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:711) ~[kubernetes-client-2.2.7.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:192) ~[kubernetes-client-2.2.7.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:392) ~[kubernetes-client-2.2.7.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation$2.apply(BaseOperation.java:362) ~[kubernetes-client-2.2.7.jar!/:na]
	at io.fabric8.openshift.api.model.DoneableImageStream.done(DoneableImageStream.java:27) ~[kubernetes-model-1.0.67.jar!/:1.0.67]
	at com.redhat.ipaas.openshift.OpenShiftServiceImpl.ensureImageStreams(OpenShiftServiceImpl.java:57) ~[openshift-0.1-SNAPSHOT.jar!/:na]
	at com.redhat.ipaas.openshift.OpenShiftServiceImpl.lambda$createOpenShiftResources$0(OpenShiftServiceImpl.java:45) ~[openshift-0.1-SNAPSHOT.jar!/:na]
	at io.fabric8.kubernetes.client.WithRequestCallable.call(WithRequestCallable.java:35) ~[kubernetes-client-2.2.7.jar!/:na]
	at com.redhat.ipaas.openshift.OpenShiftServiceImpl.createOpenShiftResources(OpenShiftServiceImpl.java:43) ~[openshift-0.1-SNAPSHOT.jar!/:na]
	at com.redhat.ipaas.rest.v1.handler.integration.IntegrationHandler.lambda$ensureOpenShiftResources$3(IntegrationHandler.java:175) ~[rest-0.1-SNAPSHOT.jar!/:na]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_111]
	at com.redhat.ipaas.rest.v1.handler.integration.IntegrationHandler.ensureOpenShiftResources(IntegrationHandler.java:175) ~[rest-0.1-SNAPSHOT.jar!/:na]
```

Setup is minishift with ipaas-dev templates.

**Comment by rhuss** [comment]
I added the missing image-stream s2i-java to the project, but get the same error.

```yml
apiVersion: v1
kind: ImageStream
metadata:
  name: s2i-java
  labels:
    app: redhat-ipaas
    component: ipaas-rest
spec:
  tags:
  - from:
      kind: DockerImage
      name: docker.io/fabric8/s2i-java:latest
    importPolicy:
      scheduled: true
    name: latest
```

**Comment by rhuss** [comment]
@jimmidyson btw, should this image stream added to our templates ? And if so, for all templates ?

**Comment by rhuss** [comment]
The builder imagestream is created on the fly and the stacktrace above happens exactly when imagestream is created. So no need to add the builder stream explicitly.
