### ISSUE TITLE
Error logged: KubernetesClientException: Resource not found

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-rest#328]
```
2017-04-24 13:01:16.131  INFO [-,,,] 1 --- [pool-4-thread-1] c.r.i.c.i.IntegrationController          : Integration 1 : Desired status "Deactivated" != current status "Activated" --> calling status change handler
2017-04-24 13:01:16.132  INFO [-,,,] 1 --- [pool-4-thread-1] c.r.i.c.i.IntegrationController          : Integration 1 : Start processing integration with DeactivateHandler
2017-04-24 13:01:16.327 ERROR [-,,,] 1 --- [pool-4-thread-1] c.r.i.c.i.IntegrationController          : Error while processing integration status for integration 1

io.fabric8.kubernetes.client.KubernetesClientException: Resource not found!
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:225) ~[kubernetes-client-2.2.13.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.edit(HasMetadataOperation.java:64) ~[kubernetes-client-2.2.13.jar!/:na]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.edit(DeploymentConfigOperationsImpl.java:69) ~[openshift-client-2.2.13.jar!/:na]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.edit(DeploymentConfigOperationsImpl.java:48) ~[openshift-client-2.2.13.jar!/:na]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.edit(DeploymentConfigOperationsImpl.java:67) ~[openshift-client-2.2.13.jar!/:na]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.edit(DeploymentConfigOperationsImpl.java:48) ~[openshift-client-2.2.13.jar!/:na]
	at com.redhat.ipaas.openshift.OpenShiftServiceImpl.lambda$scale$5(OpenShiftServiceImpl.java:85) ~[openshift-0.1-SNAPSHOT.jar!/:na]
	at io.fabric8.kubernetes.client.WithRequestCallable.call(WithRequestCallable.java:35) ~[kubernetes-client-2.2.13.jar!/:na]
	at com.redhat.ipaas.openshift.OpenShiftServiceImpl.scale(OpenShiftServiceImpl.java:84) ~[openshift-0.1-SNAPSHOT.jar!/:na]
	at com.redhat.ipaas.controllers.integration.online.DeactivateHandler.execute(DeactivateHandler.java:56) ~[controllers-0.1-SNAPSHOT.jar!/:na]
	at com.redhat.ipaas.controllers.integration.IntegrationController.lambda$callStatusChangeHandler$10(IntegrationController.java:159) ~[controllers-0.1-SNAPSHOT.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]

```

**Comment by iocanel** [comment]
There is not much to do here. We are trying to scale down a resource that is not there. Other than displaying a prettier error message there is not much we can do.

So, the question is why the resource is not there. Did it fail to create? Was it externally deleted? Do we somehow look in the wrong place? We need more feedback, to be able to do anything about it. Meanwhile I'll try to get the client to provide a better message.
