### ISSUE TITLE
Integration test failure

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-rest#387]
After merging the basepom change, I get repeatably the following exception on verification of the integration test:

```
[INFO] --- maven-failsafe-plugin:2.20:verify (default) @ runtime ---
[INFO] Failsafe report directory: /Users/roland/Development/syndesis/syndesis-rest/runtime/target/failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Syndesis REST :: Parent ............................ SUCCESS [  5.836 s]
[INFO] Syndesis REST :: Connector Catalog ................. SUCCESS [  9.660 s]
[INFO] Syndesis REST :: Core .............................. SUCCESS [  9.099 s]
[INFO] Syndesis REST :: Model ............................. SUCCESS [ 20.255 s]
[INFO] Syndesis REST :: DAO ............................... SUCCESS [ 20.372 s]
[INFO] Syndesis REST :: GitHub Access ..................... SUCCESS [ 11.987 s]
[INFO] Syndesis REST :: OpenShift Services ................ SUCCESS [ 15.896 s]
[INFO] Syndesis REST :: Project Generator ................. SUCCESS [ 20.251 s]
[INFO] Syndesis REST :: Controllers ....................... SUCCESS [ 16.948 s]
[INFO] Syndesis REST :: JsonDB ............................ SUCCESS [ 27.043 s]
[INFO] Syndesis REST :: Model2 ............................ SUCCESS [ 25.239 s]
[INFO] Syndesis REST :: Verifier .......................... SUCCESS [ 16.220 s]
[INFO] Syndesis REST :: REST .............................. SUCCESS [ 39.890 s]
[INFO] Syndesis REST :: Runtime ........................... FAILURE [04:26 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:25 min
[INFO] Finished at: 2017-06-06T15:31:53+02:00
[INFO] Final Memory: 246M/1725M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.20:verify (default) on project runtime: There was a timeout or other error in the fork -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.20:verify (default) on project runtime: There was a timeout or other error in the fork
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
```

**Comment by zregvart** [comment]
basepom enforces tests run limit, I've gradually increased that limit from the default (30sec) to 5min (300sec), this value (property `basepom.test.timeout`) can be increased even more.

The issue that bugs me is that the `runtime` module was not built for more than 5min (4:26min according to the output), so I'm inclined that the forked JVM exited with error status, @rhuss can you take a look at the logs of the tests?

**Comment by rhuss** [comment]
@zregvart Increasing the timeout to 600s (using -Dbasepom.test.timeout=600) to the build didn't help so it's indeed something different. Unfortunately there also no test failures for the `maven-failsafe-plugin` neither any error in Keycloak's server.log

Actually, the `failsafe-summary.xml` looks like:

```xml
<failsafe-summary result="254" timeout="true">
    <completed>0</completed>
    <errors>0</errors>
    <failures>0</failures>
    <skipped>0</skipped>
    <failureMessage xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
</failsafe-summary>
```

So maybe it's a different timeout which kills the build ?

**Comment by rhuss** [comment]
Running with `-X` reveals:

```
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-failsafe-plugin:2.20:integration-test from plugin re
alm ClassRealm[plugin>org.apache.maven.plugins:maven-failsafe-plugin:2.20, parent: sun.misc.Launcher$AppClas
sLoader@5c647e05]
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-failsafe-plugin:2.20:integration-test' with basic c
onfigurator -->
[DEBUG]   (s) additionalClasspathElements = [/Users/roland/Development/syndesis/syndesis-rest/runtime/target
/classes]
[DEBUG]   (s) argLine = -javaagent:/Users/roland/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco
.agent-0.7.9-runtime.jar=destfile=/Users/roland/Development/syndesis/syndesis-rest/runtime/target/jacoco-it.
exec -Xmx256m -Dfile.encoding=UTF-8
[DEBUG]   (s) basedir = /Users/roland/Development/syndesis/syndesis-rest/runtime
[DEBUG]   (s) childDelegation = false
[DEBUG]   (s) classpathDependencyExcludes = []
[DEBUG]   (s) defaultClassesDirectory = /Users/roland/Development/syndesis/syndesis-rest/runtime/target/clas
ses
[DEBUG]   (s) dependenciesToScan = []
[DEBUG]   (s) disableXmlReport = false
[DEBUG]   (s) enableAssertions = true
[DEBUG]   (f) encoding = UTF-8
[DEBUG]   (f) forkCount = 1
[DEBUG]   (s) forkMode = once
[DEBUG]   (s) forkedProcessExitTimeoutInSeconds = 30
[DEBUG]   (s) forkedProcessTimeoutInSeconds = 30
```

So it seems there is yet another timeout, this time its 30s (and probably for a single test)

**Comment by zregvart** [comment]
Awesome @rhuss, in hindsight I should have set the property `basepom.failsafe.timeout` not `basepom.test.timeout`, can you take a look at the rework I did in the #390
