### ISSUE TITLE
Error: Expected BEGIN_OBJECT but was STRING during create integration

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-rest#534]
Can't create integration on syndesis-staging because rest fails with this error:
```
2017-08-23 08:50:45.376  INFO [-,,,] 1 --- [pool-4-thread-1] i.s.c.integration.IntegrationController  : Integration 5 : Start processing integration with ActivateHandler
2017-08-23 08:50:45.376  INFO [-,,,] 1 --- [pool-4-thread-1] i.s.c.integration.IntegrationController  : Integration 5 : Setting status to Pending
2017-08-23 08:50:46.202  INFO [-,,,] 1 --- [pool-5-thread-1] i.s.c.integration.IntegrationController  : Integration -KsDGedpYDLM4EN0HL4d : Desired status "Activated" != current status "Pending" --> calling status change handler
2017-08-23 08:50:46.202  INFO [-,,,] 1 --- [pool-4-thread-1] i.s.c.integration.IntegrationController  : Integration -KsDGedpYDLM4EN0HL4d : Start processing integration with ActivateHandler
2017-08-23 08:50:46.338 ERROR [-,,,] 1 --- [pool-4-thread-1] i.s.c.i.online.ActivateHandler           : Integration -KsDGedpYDLM4EN0HL4d : Failure

io.syndesis.core.SyndesisServerException: An error has occurred.
	at io.syndesis.core.SyndesisServerException.launderThrowable(SyndesisServerException.java:53) ~[core-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
	at io.syndesis.core.SyndesisServerException.launderThrowable(SyndesisServerException.java:44) ~[core-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
	at io.syndesis.controllers.integration.online.ActivateHandler.getGitHubUser(ActivateHandler.java:197) ~[controllers-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
	at io.syndesis.controllers.integration.online.ActivateHandler.execute(ActivateHandler.java:106) ~[controllers-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
	at io.syndesis.controllers.integration.IntegrationController.lambda$callStatusChangeHandler$10(IntegrationController.java:173) [controllers-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: java.io.IOException: Parse exception converting JSON to object
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:424) ~[org.eclipse.egit.github.core-2.1.5.jar!/:na]
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:403) ~[org.eclipse.egit.github.core-2.1.5.jar!/:na]
	at org.eclipse.egit.github.core.client.GitHubClient.parseError(GitHubClient.java:514) ~[org.eclipse.egit.github.core-2.1.5.jar!/:na]
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:547) ~[org.eclipse.egit.github.core-2.1.5.jar!/:na]
	at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:740) ~[org.eclipse.egit.github.core-2.1.5.jar!/:na]
	at org.eclipse.egit.github.core.service.UserService.getUser(UserService.java:95) ~[org.eclipse.egit.github.core-2.1.5.jar!/:na]
	at io.syndesis.github.GitHubServiceImpl.getApiUser(GitHubServiceImpl.java:82) ~[github-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
	at io.syndesis.controllers.integration.online.ActivateHandler.getGitHubUser(ActivateHandler.java:195) ~[controllers-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
	... 7 common frames omitted
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[gson-2.8.1.jar!/:na]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.1.jar!/:na]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.1.jar!/:na]
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:422) ~[org.eclipse.egit.github.core-2.1.5.jar!/:na]
	... 14 common frames omitted
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[gson-2.8.1.jar!/:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[gson-2.8.1.jar!/:na]
	... 17 common frames omitted
```

**Comment by jludvice** [comment]
CC @rhuss @jknetl
