### ISSUE TITLE
Couldn't find the user of the integration

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis-rest#718]
I think there might be some out of sync data with the default Integrations already available.

Each time I try to start one of them, for instance, the simple `Couldn't find the user of the integration`

I get this error in `syndesis-rest` logs:

```
2017-10-17 19:44:15.361 ERROR [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.IntegrationController  : Error while processing integration status for integration 3

java.lang.IllegalStateException: Couldn't find the user of the integration
	at io.syndesis.controllers.integration.online.ActivateHandler.lambda$countIntegrations$1(ActivateHandler.java:169) ~[controllers-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_131]
	at io.syndesis.controllers.integration.online.ActivateHandler.countIntegrations(ActivateHandler.java:169) ~[controllers-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
	at io.syndesis.controllers.integration.online.ActivateHandler.execute(ActivateHandler.java:66) ~[controllers-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
	at io.syndesis.controllers.integration.IntegrationController.lambda$callStatusChangeHandler$10(IntegrationController.java:175) ~[controllers-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

```

The code at the indicate line is:

```java
        String username = integration.getUserId().orElseThrow(() -> new IllegalStateException("Couldn't find the user of the integration"));
```
https://github.com/syndesisio/syndesis-rest/blob/master/controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java#L108

**Comment by zregvart** [comment]
@paoloantinori this is caused by incomplete data in `demo-data.json` I usually don't load the demo data when developing. That is set `DEMO_DATA_ENABLED` to `false` when creating new app on openshift or changing the deployment's environment manually and deleting all rows from the jsondb table in PostgreSQL running in syndesis-db pod beforehand.

When setting up the app you can pass env variables like (adapted from [quickstart](https://syndesis.io/quickstart/))
```
$ oc new-app syndesis-dev-restricted \
    -p ROUTE_HOSTNAME=syndesis.$(minishift ip).nip.io \
    -p OPENSHIFT_MASTER=$(oc whoami --show-server) \
    -p OPENSHIFT_PROJECT=$(oc project -q) \
    -p OPENSHIFT_OAUTH_CLIENT_SECRET=$(oc sa get-token syndesis-oauth-client) \
    -p DEMO_DATA_ENABLED=false
```

**Comment by zregvart** [comment]
And we should have a discussion if we still need demo data, or if it should be loaded by default.

**Comment by paoloantinori** [comment]
Thanks @zregvart. I'd say that we have to at least mention the issue in the quickstart or suggest a different value for `DEMO_DATA_ENABLED` property.

**Comment by KurtStam** [comment]
@zregvart my preference is to keep the demo data, and to add the missing data. What data is missing?

**Comment by rhuss** [comment]
The user is currently used as part of a label to a `Deployment` so that we can count how many integrations a user has deployed. Actually, the limit should be global, but currently its user based. Hence the UID is required for this use case.
